[package]
name = "outro_08"
version = "0.1.0"
edition = "2021"

[dependencies]
ticket_fields = { path = "../../../helpers/ticket_fields" }
without_channels = { path = "../../07_threads/13_without_channels" }

tokio = { version = "1", features = ["full"] }
axum = "0.8.9"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.150"

[dev-dependencies]
axum-test = "21.0.0"
